/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) MNovus. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import {
  app,
  BrowserWindow,
  ipcMain,
  dialog,
  Menu,
  MenuItem,
  autoUpdater,
  ipcRenderer,
} from "electron";
import fs from "fs";
import path from "path";
import Store from "electron-store";
import { PythonShell } from "python-shell";
import clipboardy from "clipboardy";
import os from "os";
import * as pty from "node-pty";
import * as chokidar from "chokidar";
import { execFile } from "child_process";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const SELECTED_FOLDER_STORE_NAME = "selected-folder";
const SETTINGS_STORE_NAME = "settings-store";
const INTERPRETER_STORE_NAME = "interpreter-store";
const store = new Store();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;
let splashWindow: BrowserWindow;
let ptyProcess: pty.IPty;

const get_files = (path: string) => {
  const files = fs.readdirSync(path, {
    recursive: true,
    withFileTypes: true,
  });
  // return files.map(file => ({...file, is_dir: file.isDirectory(), is_symlink: file.isSymbolicLink()})).filter(file => file.name != '.git')
  return files
    .map((file) => ({ ...file, is_dir: file.isDirectory() }))
    .filter((file) => file.name != ".git");
};

ipcMain.handle("get-folder", async (event, data) => {
  // @ts-ignore
  return store.get(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("clear-folder", () => {
  // @ts-ignore
  store.delete(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("create-project-anantam-config-file", async (event, data) => {
  const content = `{\n    "project_type": "anantam",\n    "interpreter_path": "'${data.interpreter_path}'",\n    "variables": true,\n    "file_suggestion": false\n}`;
  fs.writeFileSync(data.path, content);
});
ipcMain.on("create-project-anantam-file", async (event, data) => {
  fs.writeFileSync(data.path, data.content);
});

ipcMain.on("create-folder", async (event, data) => {
  fs.mkdirSync(data.path);
});

ipcMain.on("set-folder", (event, folder: string) => {
  let structure = undefined;

  const tree = get_files(folder);
  structure = {
    name: folder,
    root: folder,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.handle("open-set-folder", async (event, data) => {
  const folder = await dialog.showOpenDialog(mainWindow, {
    properties: ["openDirectory"],
  });
  let structure = undefined;
  if (!folder.canceled) {
    console.log("folder", folder.filePaths[0]);
    const tree = get_files(folder.filePaths[0]);
    structure = {
      // name: path.dirname(folder.filePaths[0]),
      name: folder.filePaths[0],
      root: folder.filePaths[0],
      tree,
    };
    // @ts-ignore
    store.set(SELECTED_FOLDER_STORE_NAME, structure);
    // ipcMain.emit('new-folder-opened')
    mainWindow.webContents.send("new-folder-opened");
  }
});

ipcMain.on("refresh-window", (event, folder) => {
  let structure = undefined;

  const tree = get_files(folder);
  structure = {
    name: folder,
    root: folder,
    tree,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("create-folder", async (event, data) => {
  //   path: data.path,
  // fileName: string
  //   rootPath:  data.rootPath

  const new_folder = fs.mkdirSync(data.path);

  const tree = get_files(data.rootPath);
  const structure = {
    // name: path.dirname(data.rootPath),
    name: data.rootPath,
    root: data.rootPath,
    tree,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);

  const newFolder = {
    name: data.fileName,
    parentPath: data.path,
    path: data.path,
    is_dir: true,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("create-file", async (event, data) => {
  //   path: data.path,
  // fileName: string
  //   rootPath:  data.rootPath

  const new_file = fs.writeFileSync(data.path, "");

  const tree = get_files(data.rootPath);
  const structure = {
    // name: path.dirname(data.rootPath),
    name: data.rootPath,
    root: data.rootPath,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);

  const newfile = {
    name: data.fileName,
    parentPath: data.path,
    path: data.path,
    is_dir: false,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("set-settings", (event, data) => {
  // @ts-ignore
  store.set(SETTINGS_STORE_NAME, data);
});

ipcMain.handle("get-settings", async (event) => {
  // @ts-ignore
  return store.get(SETTINGS_STORE_NAME);
});

ipcMain.on("set-interpreter", (event, data) => {
  // @ts-ignore
  store.set(INTERPRETER_STORE_NAME, data);
});

ipcMain.handle("get-interpreter", async (event) => {
  // @ts-ignore
  return store.get(INTERPRETER_STORE_NAME);
});

ipcMain.handle("dialog:select-interpreter", async (event) => {
  const result = await dialog.showOpenDialog(
    new BrowserWindow({
      alwaysOnTop: true,
    }),
    {
      title: "Select Interpreter",
      properties: ["openFile"],
      filters: [
        { name: "All Files", extensions: ["*"] }, // Allow all file extensions
      ],
    }
  );

  if (result.canceled || result.filePaths.length === 0) {
    return null; // No file selected
  }

  const filePath = result.filePaths[0]; // Get the selected file path

  // Check if the file is a valid interpreter
  const isValidInterpreter = await new Promise((resolve) => {
    execFile(filePath, ["--version"], (error, stdout, stderr) => {
      if (error) {
        resolve(false); // Not valid if it fails to execute
      } else if (stdout.toLowerCase().includes("python")) {
        resolve(true); // Valid Python interpreter
      } else {
        resolve(false); // Not valid if output doesn't contain "python"
      }
    });
  });

  if (!isValidInterpreter) {
    // Show an alert if the interpreter is not valid
    await dialog.showMessageBox(
      new BrowserWindow({
        alwaysOnTop: true,
      }),
      {
        type: "error",
        title: "Invalid Interpreter",
        message: "The selected file is not a valid Python interpreter.",
      }
    );
    return null; // Return null to indicate invalid selection
  }

  return filePath; // Return the valid interpreter path
});

ipcMain.handle("get-file-content", async (event, path) => {
  try {
    const file_content = fs.readFileSync(path, "utf8");
    return file_content;
  } catch {
    return "Got error fetching file content";
  }
});

ipcMain.handle("run-code", async (event, data) => {
  if (!data.path.endsWith(".py")) {
    if (data.path.endsWith(".js")) {
      ptyProcess.write(`node ${data.path}\n`);
    }
    return;
  }

  ptyProcess.write(`${data.script} ${data.path}\n`);
});

ipcMain.on("coming-soon-dialog", async (event, data) => {
  await dialog.showMessageBox(mainWindow, {
    title: "Coming Soon",
    type: "info",
    buttons: ["OK", "Cancel"],
    message: "This feature is coming soon!",
  });
});

function deleteDirectoryRecursive(dirPath: string) {
  // Get the list of files and subdirectories in the directory
  const files = fs.readdirSync(dirPath);

  // Loop through the files and delete them
  files.forEach((file) => {
    const filePath = path.join(dirPath, file);

    // Check if it's a directory
    if (fs.statSync(filePath).isDirectory()) {
      deleteDirectoryRecursive(filePath); // Recursively delete subdirectory
    } else {
      fs.unlinkSync(filePath); // Delete file
    }
  });

  // Finally, remove the empty directory
  fs.rmdirSync(dirPath);
}

let copiedFile: any = null; // Variable to store copied file data

ipcMain.on("new-folder-input", (event, data) => {
  event.sender.send("command-create-folder", data);
});
ipcMain.on("new-file-input", (event, data) => {
  event.sender.send("command-create-file", data);
});

ipcMain.on("folder-contextmenu", async (event, data) => {
  const template: any = [
    {
      label: "New File...",
      click: () => {
        event.sender.send("command-create-file", data);
      },
      visible: data.type == "folder",
    },
    {
      label: "New Folder...",
      click: () => {
        event.sender.send("command-create-folder", data);
      },
      visible: data.type == "folder",
    },
    { type: "separator" },
    {
      label: "Cut",
      role: "cut",
      click: () => {
        // Implement Cut functionality here
      },
      enabled: true, // Ensure that enabled is set if needed
    },
    {
      label: "Copy",
      role: "copy",
      click: () => {
        const filePath = data.path;

        // Read the file content
        const fileContent = fs.readFileSync(filePath);

        // Store the file content and name in a variable to be accessed later
        copiedFile = {
          name: path.basename(filePath),
          content: fileContent,
        };

        console.log("File copied to clipboard");
      },
      enabled: true,
    },
    {
      label: "Paste",
      role: "paste",
      click: () => {
        if (copiedFile) {
          const destinationPath = path.join(data.rootPath, copiedFile.name);

          // Write the file to the rootPath
          fs.writeFileSync(destinationPath, copiedFile.content);

          console.log(`File pasted to ${destinationPath}`);

          // Reset copiedFile after pasting
          copiedFile = null;
        } else {
          console.log("No file to paste");
        }
      },
    },
    {
      label: "Copy Relative Path",
      click: () => {
        const filePath = data.path;

        // Calculate the relative path from rootPath
        const relativePath = path.relative(data.rootPath, filePath);

        // Copy the relative path to the clipboard
        clipboardy.write(relativePath);
      },
    },
    { type: "separator" },
    {
      label: "Rename",
      role: "editMenu",
      click: () => {
        // Implement Rename functionality here
      },
    },
    {
      label: "Delete",
      click: async () => {
        console.log(data);
        if (data.type === "file") {
          fs.rmSync(data.path);
        } else {
          deleteDirectoryRecursive(data.path);
        }
      },
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  menu.popup({ window: BrowserWindow.fromWebContents(event.sender) });
});

ipcMain.on("save-file", async (event, data) => {
  const file_content = fs.writeFileSync(data.path, data.content);
  console.log("file writen");
});

ipcMain.on("minimize", () => {
  mainWindow.minimize();
});

ipcMain.on("maximize", () => {
  if (mainWindow.isMaximized()) {
    mainWindow.minimize();
  } else {
    mainWindow.maximize();
  }
});

ipcMain.on("close", () => {
  mainWindow.close();
});

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: path.join(__dirname, "assets", "logo.png"),
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      nodeIntegration: true,
    },
    zoomToPageWidth: true,
  });

  mainWindow.setMenuBarVisibility(false);

  mainWindow.maximize();

  // @ts-ignore
  const cwd = store.get(SELECTED_FOLDER_STORE_NAME).root;

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  const shell = os.platform() === "win32" ? "powershell.exe" : "bash";

  ptyProcess = pty.spawn(shell, [], {
    name: "xterm-color",
    cols: 80,
    rows: 30,
    cwd: cwd || process.env.HOME,
    env: process.env,
  });

  ptyProcess.onData(function (data) {
    mainWindow.webContents.send("terminal.incomingData", data);
    console.log("Data sent");
  });

  ipcMain.on("terminal.keystroke", (event, key) => {
    ptyProcess.write(key);
  });

  ipcMain.on("terminal.resize", (event, data) => {
    ptyProcess.resize(data.cols, data.rows);
  });

  ipcMain.on("terminal.write", (event, line) => {
    ptyProcess.write(line);
  });

  ipcMain.handle("open-folder", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });
    let structure = undefined;
    if (!folder.canceled) {
      const tree = get_files(folder.filePaths[0]);
      structure = {
        // name: path.dirname(folder.filePaths[0]),
        name: folder.filePaths[0],
        root: folder.filePaths[0],
        tree,
      };
      // @ts-ignore
      store.set(SELECTED_FOLDER_STORE_NAME, structure);
    }

    return structure;
  });

  // Register the ipcMain handler for 'dialog:openFolder'
  ipcMain.handle("open-folder-new-project", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });

    return folder.filePaths[0]; // Return the selected folder pathr;
  });

  mainWindow.once("ready-to-show", () => {
    mainWindow.show(); // Show the main window
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow(); // Create the main window

  // Check for updates on startup
  autoUpdater.checkForUpdates();

  autoUpdater.on("update-available", () => {
    dialog.showMessageBox({
      type: "info",
      title: "Update Available",
      message:
        "A new version of the Anantam is available. The update will be downloaded and installed automatically.",
    });
  });

  autoUpdater.on("update-downloaded", () => {
    dialog
      .showMessageBox({
        type: "info",
        title: "Update Ready",
        message:
          "The update has been downloaded. Anantam will restart to apply the update.",
      })
      .then(() => {
        autoUpdater.quitAndInstall();
      });
  });

  autoUpdater.on("error", (error) => {
    console.error("Update error:", error);
  });
});
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
