/*---------------------------------------------------------------------------------------------
 *  Copyright (c) MNovus. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { app, BrowserWindow, ipcMain, dialog, Menu, MenuItem } from "electron";
import fs from "fs";
import path from "path";
import Store from "electron-store";
import startServer from "../server/index";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const SELECTED_FOLDER_STORE_NAME = "selected-folder";
const store = new Store();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;
let splashWindow: BrowserWindow;

const WindowsTemplate: any = [
  {
    label: "File",
    submenu: [
      { label: "New Text File" },
      { label: "New File" },
      { label: "New Window" },
      { type: "separator" },
      { label: "Open..." },
      {
        label: "Open Folder...",
        click: async () => {
          const folder = await dialog.showOpenDialog(mainWindow, {
            properties: ["openDirectory"],
          });
          let structure = undefined;
          if (!folder.canceled) {
            const tree = get_files(folder.filePaths[0]);
            structure = {
              name: folder.filePaths[0],
              root: folder.filePaths[0],
              tree,
            };
            // @ts-ignore
            store.set(SELECTED_FOLDER_STORE_NAME, structure);
            mainWindow.webContents.send("new-folder-opened");
          }
        },
      },
      { type: "separator" },
      { label: "Save" },
      { label: "Save As..." },
      { label: "Save All" },
      { type: "separator" },
      { label: "Revert File" },
      { label: "Close Editor", role: "close" },
    ],
  },
  {
    label: "Edit",
    submenu: [
      { role: "undo" },
      { role: "redo" },
      { type: "separator" },
      { role: "cut" },
      { role: "copy" },
      { role: "paste" },
      { role: "delete" },
      { type: "separator" },
      { role: "selectAll" },
    ],
  },
  {
    label: "Selection",
    submenu: [
      { role: "selectAll" },
      { label: "Expand Selection" },
      { label: "Shrink Selection" },
      { type: "separator" },
      { label: "Copy Line Up" },
      { label: "Copy Line Down" },
      { label: "Move Line Up" },
      { label: "Move Line Down" },
      { label: "Duplicate Selection" },
      { type: "separator" },
      { label: "Add Cursor Above" },
      { label: "Add Cursor Below" },
      { label: "Add Cursor to Line Ends" },
      { label: "Add Next Occurrence" },
      { label: "Add Previous Occurrence" },
      { label: "Select All Occurrence" },
      { type: "separator" },
      { label: "Switch Control+Click to Multi-Cursor" },
      { label: "Column Selection Mode" },
    ],
  },
  {
    label: "View",
    submenu: [
      { label: "Command Pallete" },
      { label: "Open View" },
      { type: "separator" },
      {
        label: "Appearance",
        submenu: [
          { label: "Full Screen" },
          { label: "Zen Mode" },
          { label: "Center Layout" },
        ],
      },
      {
        label: "Editor Layout",
        submenu: [
          { label: "Split Up" },
          { label: "Split Down" },
          { label: "Split Left" },
          { label: "Split Right" },
          { type: "separator" },
          { label: "Split in Group" },
          { type: "separator" },
          { label: "Move Editor into New Window" },
          { label: "Copy Editor into New Window" },
          { type: "separator" },
          { label: "Single" },
          { label: "Two Columns" },
          { label: "Three Columns" },
          { label: "Two Rows" },
          { label: "Grid (2x2)" },
          { label: "Two Rows Right" },
          { label: "Two Columns Bottom" },
        ],
      },
      { type: "separator" },
      { label: "Explorer" },
      { label: "Search" },
      { label: "Source Control" },
      { label: "Run" },
      { label: "Extensions" },
      { type: "separator" },
      { label: "Problems" },
      { label: "Output" },
      { label: "Debug Console" },
      { label: "Terminal" },
      { type: "separator" },
      { label: "Word Wrap" },
    ],
  },
  {
    label: "Go",
    submenu: [
      { label: "Back" },
      { label: "Forward", enabled: false },
      { label: "Last Edit Location" },
      {
        label: "Switch Editor",
        submenu: [
          { label: "Next Editor" },
          { label: "Previous Editor" },
          { type: "separator" },
          { label: "Next Used Editor" },
          { label: "Previous Used Editor" },
          { type: "separator" },
          { label: "Next Editor in Group" },
          { label: "Previous Editor in Group" },
        ],
      },
      {
        label: "Switch Group",
        submenu: [
          { label: "Group 1" },
          { label: "Group 2" },
          { label: "Group 3", enabled: false },
          { label: "Group 4", enabled: false },
          { label: "Group 5", enabled: false },
          { type: "separator" },
          { label: "Next Group", enabled: false },
          { label: "Previous Group", enabled: false },
        ],
      },
      { type: "separator" },
      { label: "Go to File" },
      { label: "Go to Symbol in Workspace" },
      { type: "separator" },
      { label: "Go to Symbol in Editor" },
      { label: "Go to Definition" },
      { label: "Go to Declaration" },
      { label: "Go to Type Definition" },
      { label: "Go to Implementations" },
      { label: "Go to References" },
      { type: "separator" },
      { label: "Go to Line/Column" },
      { label: "Go to Bracket" },
      { type: "separator" },
      { label: "Next Problem" },
      { label: "Previous Problem" },
      { type: "separator" },
      { label: "Next Change" },
      { label: "Previous Change" },
    ],
  },
  {
    label: "Run",
    submenu: [
      { label: "Start Debugging" },
      { label: "Run Without Debugging" },
      { label: "Stop Debugging", enabled: false },
      { label: "Restart Debugging", enabled: false },
      { type: "separator" },
      { label: "Open Configuration", enabled: false },
      { label: "Add Configuration", enabled: true },
      { type: "separator" },
      { label: "Step Over", enabled: false },
      { label: "Step Into", enabled: false },
      { label: "Step Out", enabled: false },
      { label: "Continue", enabled: false },
      { type: "separator" },
      { label: "Toggle Breakpoint" },
      { label: "New Breakpoint" },
      {
        role: "zoom",
        submenu: [
          { label: "Conditional Breakpoint" },
          { label: "Edit Breakpoint" },
          { label: "Inline Breakpoint" },
          { label: "Function Breakpoint..." },
          { label: "Logpoint..." },
        ],
      },
      { type: "separator" },
      { label: "Enable All Breakpoints" },
      { label: "Disable All Breakpoints" },
      { label: "Remove All Breakpoints" },
      { type: "separator" },
      { label: "Install Additional Debugger..." },
    ],
  },
  {
    label: "Terminal",
    submenu: [
      { label: "New Terminal" },
      { label: "Split Terminal", enabled: false },
      { type: "separator" },
      { label: "Run Task" },
      { label: "Run Build Task" },
      { label: "Run Active Task" },
      { label: "Run Selected Task" },
      { type: "separator" },
      { label: "Show Running Task", enabled: false },
      { label: "Restart Running Task", enabled: false },
      { label: "Terminate Task", enabled: false },
      { type: "separator" },
      { label: "Configure Task...", enabled: false },
      { label: "Configure Default Build Task...", enabled: false },
      { role: "zoom" },
    ],
  },
  {
    label: "Window",
    submenu: [
      { role: "minimize" },
      { role: "zoom" },
      { label: "Tile Window to Left of Screen" },
      { label: "Tile Window to Right of Screen" },
      { label: "Replace Tiled Window" },
      { type: "separator" },
      { label: "Remove Window From Set", enabled: false },
      { type: "separator" },
      { label: "Switch Window" },
      { type: "separator" },
      { label: "Bring All Front" },
    ],
  },
  {
    role: "help",
    submenu: [
      { label: "Welcome" },
      { label: "Show All Commands" },
      { label: "Documentation" },
      { label: "Editor Playground" },
      { label: "Show Release Notes" },
      { label: "Check for Updates" },
      { type: "separator" },
      { label: "Report a Bug" },
      { label: "Request a Feature" },
    ],
  },
];

const menu = Menu.buildFromTemplate(WindowsTemplate);
Menu.setApplicationMenu(menu);

const get_files = (path: string) => {
  const files = fs.readdirSync(path, {
    recursive: true,
    withFileTypes: true,
  });
  // return files.map(file => ({...file, is_dir: file.isDirectory(), is_symlink: file.isSymbolicLink()})).filter(file => file.name != '.git')
  return files
    .map((file) => ({ ...file, is_dir: file.isDirectory() }))
    .filter((file) => file.name != ".git");
};

ipcMain.handle("get-folder", async (event, data) => {
  // @ts-ignore
  return store.get(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("clear-folder", () => {
  // @ts-ignore
  store.delete(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("create-project-anantam-config-file", async (event, data) => {
  const content = `project_type: anantam\ninterpreter_path: ${data.interpreter_path}\nvariables: true`;
  fs.writeFileSync(data.path, content);
});
ipcMain.on("create-project-anantam-file", async (event, data) => {
  fs.writeFileSync(data.path, data.content);
});

ipcMain.on("create-folder", async (event, data) => {
  fs.mkdirSync(data.path);
});

ipcMain.on("set-folder", (event, folder: string) => {
  let structure = undefined;

  const tree = get_files(folder);
  structure = {
    name: folder,
    root: folder,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("create-file", async (event, data) => {
  //   path: data.path,
  // fileName: string
  //   rootPath:  data.rootPath

  const new_file = fs.writeFileSync(data.path, "");

  const tree = get_files(data.rootPath);
  const structure = {
    // name: path.dirname(data.rootPath),
    name: data.rootPath,
    root: data.rootPath,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);

  const newfile = {
    name: data.fileName,
    parentPath: data.path,
    path: data.path,
    is_dir: false,
  };

  event.sender.send("command-update-folder-structure", newfile);
});

ipcMain.handle("get-file-content", async (event, path) => {
  const file_content = fs.readFileSync(path, "utf8");
  return file_content;
});

ipcMain.on("folder-contextmenu", async (event, data) => {
  const template: any = [
    {
      label: "New File...",
      click: () => {
        event.sender.send("command-create-file", data);
      },
      visible: data.type == "folder",
    },
    {
      label: "New Folder...",
      visible: data.type == "folder",
    },
    { type: "separator" },
    {
      label: "Cut",
      role: "cut",
      click: () => {
        // Implement Cut functionality here
      },
      enabled: true, // Ensure that enabled is set if needed
    },
    {
      label: "Copy",
      role: "copy",
      click: () => {
        // Implement Copy functionality here
      },
      enabled: true,
    },
    {
      label: "Paste",
      enabled: false, // Disabled by default
      role: "paste",
      click: () => {
        // Implement Paste functionality here
      },
    },
    { type: "separator" },
    {
      label: "Copy Path",
      role: "copy",
      click: () => {
        // Implement Copy Path functionality here
      },
    },
    {
      label: "Copy Relative Path",
      click: () => {
        // Implement Copy Relative Path functionality here
      },
    },
    { type: "separator" },
    {
      label: "Rename",
      role: "editMenu",
      click: () => {
        // Implement Rename functionality here
      },
    },
    {
      label: "Delete",
      role: "delete",
      click: () => {
        // Implement Delete functionality here
      },
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  menu.popup({ window: BrowserWindow.fromWebContents(event.sender) });
});

ipcMain.on("save-file", async (event, data) => {
  const file_content = fs.writeFileSync(data.path, data.content);
  console.log("file writen");
});

// const createSplashScreen = (): void => {
//   splashWindow = new BrowserWindow({
//     width: 1200,
//     height: 900,
//     // frame: false,
//     // alwaysOnTop: true,
//     webPreferences: {
//       nodeIntegration: true,
//       contextIsolation: false,
//     },
//   });

//   splashWindow.loadFile("splash.html");
// };

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    icon: path.join(__dirname, "public", "logo.ico"),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.maximize();

  // mainWindow.setMenuBarVisibility(false);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  ipcMain.handle("open-folder", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });
    let structure = undefined;
    if (!folder.canceled) {
      const tree = get_files(folder.filePaths[0]);
      structure = {
        // name: path.dirname(folder.filePaths[0]),
        name: folder.filePaths[0],
        root: folder.filePaths[0],
        tree,
      };
      // @ts-ignore
      store.set(SELECTED_FOLDER_STORE_NAME, structure);
    }

    return structure;
  });

  // Register the ipcMain handler for 'dialog:openFolder'
  ipcMain.handle("open-folder-new-project", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });

    return folder.filePaths[0]; // Return the selected folder pathr;
  });

  mainWindow.once("ready-to-show", () => {
    // splashWindow.close(); // Close the splash screen
    mainWindow.show(); // Show the main window
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  // createSplashScreen(); // Show the splash screen first
  createWindow(); // Create the main window
  startServer();
});
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
