/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) MNovus. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import {
  app,
  BrowserWindow,
  ipcMain,
  dialog,
  Menu,
  MenuItem,
  autoUpdater,
  globalShortcut,
} from "electron";
import fs from "fs";
import Store from "electron-store";
import os from "os";
import * as pty from "node-pty";
import { execFile } from "child_process";
import XLSX from "xlsx";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const TOOLS_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const SELECTED_FOLDER_STORE_NAME = "selected-folder";
const SETTINGS_STORE_NAME = "settings-store";
const INTERPRETER_STORE_NAME = "interpreter-store";
const DATASTUDIO_VARIABLES_STORE_NAME = " datastudio-variables-store";
const store = new Store();

interface Variable {
  name: string;
  type: string;
  value: string | number | boolean | null;
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow;
let splashWindow: BrowserWindow;
let toolsWindow: BrowserWindow;
let dataStudio: BrowserWindow;
let ptyProcess: pty.IPty;

const get_files = (path: string) => {
  const files = fs.readdirSync(path, {
    recursive: true,
    withFileTypes: true,
  });
  // return files.map(file => ({...file, is_dir: file.isDirectory(), is_symlink: file.isSymbolicLink()})).filter(file => file.name != '.git')
  return files
    .map((file) => ({ ...file, is_dir: file.isDirectory() }))
    .filter((file) => file.name != ".git");
};

ipcMain.handle("get-folder", async (event, data) => {
  // @ts-ignore
  return store.get(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("clear-folder", () => {
  // @ts-ignore
  store.delete(SELECTED_FOLDER_STORE_NAME);
});

ipcMain.on("create-project-anantam-config-file", async (event, data) => {
  const content = `{\n    "project_type": "anantam",\n    "interpreter_path": "'${data.interpreter_path}'",\n    "variables": true,\n    "file_suggestion": false\n}`;
  fs.writeFileSync(data.path, content);
});
ipcMain.on("create-project-anantam-file", async (event, data) => {
  fs.writeFileSync(data.path, data.content);
});

ipcMain.on("create-folder", async (event, data) => {
  fs.mkdirSync(data.path);
});

ipcMain.on("set-folder", (event, folder: string) => {
  let structure = undefined;

  const tree = get_files(folder);
  structure = {
    name: folder,
    root: folder,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.handle("open-set-folder", async (event, data) => {
  const folder = await dialog.showOpenDialog(mainWindow, {
    properties: ["openDirectory"],
  });
  let structure = undefined;
  if (!folder.canceled) {
    console.log("folder", folder.filePaths[0]);
    const tree = get_files(folder.filePaths[0]);
    structure = {
      // name: path.dirname(folder.filePaths[0]),
      name: folder.filePaths[0],
      root: folder.filePaths[0],
      tree,
    };
    // @ts-ignore
    store.set(SELECTED_FOLDER_STORE_NAME, structure);
    // ipcMain.emit('new-folder-opened')
    mainWindow.webContents.send("new-folder-opened");
  }
});

ipcMain.on("refresh-window", (event, folder) => {
  let structure = undefined;

  const tree = get_files(folder);
  structure = {
    name: folder,
    root: folder,
    tree,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("create-folder", async (event, data) => {
  //   path: data.path,
  // fileName: string
  //   rootPath:  data.rootPath

  const new_folder = fs.mkdirSync(data.path);

  const tree = get_files(data.rootPath);
  const structure = {
    // name: path.dirname(data.rootPath),
    name: data.rootPath,
    root: data.rootPath,
    tree,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);

  const newFolder = {
    name: data.fileName,
    parentPath: data.path,
    path: data.path,
    is_dir: true,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("create-file", async (event, data) => {
  //   path: data.path,
  // fileName: string
  //   rootPath:  data.rootPath

  const new_file = fs.writeFileSync(data.path, "");

  const tree = get_files(data.rootPath);
  const structure = {
    // name: path.dirname(data.rootPath),
    name: data.rootPath,
    root: data.rootPath,
    tree,
  };
  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);

  const newfile = {
    name: data.fileName,
    parentPath: data.path,
    path: data.path,
    is_dir: false,
  };

  // @ts-ignore
  store.set(SELECTED_FOLDER_STORE_NAME, structure);
  mainWindow.webContents.send("new-folder-opened");
});

ipcMain.on("set-settings", (event, data) => {
  // @ts-ignore
  store.set(SETTINGS_STORE_NAME, data);
});

ipcMain.handle("get-settings", async (event) => {
  // @ts-ignore
  return store.get(SETTINGS_STORE_NAME);
});

ipcMain.on("set-interpreter", (event, data) => {
  // @ts-ignore
  store.set(INTERPRETER_STORE_NAME, data);
});

ipcMain.handle("get-interpreter", async (event) => {
  // @ts-ignore
  return store.get(INTERPRETER_STORE_NAME);
});

ipcMain.handle("dialog:select-interpreter", async (event) => {
  const result = await dialog.showOpenDialog(
    new BrowserWindow({
      alwaysOnTop: true,
    }),
    {
      title: "Select Interpreter",
      properties: ["openFile"],
      filters: [
        { name: "All Files", extensions: ["*"] }, // Allow all file extensions
      ],
    }
  );

  if (result.canceled || result.filePaths.length === 0) {
    return null; // No file selected
  }

  const filePath = result.filePaths[0]; // Get the selected file path

  // Check if the file is a valid interpreter
  const isValidInterpreter = await new Promise((resolve) => {
    execFile(filePath, ["--version"], (error, stdout, stderr) => {
      if (error) {
        resolve(false); // Not valid if it fails to execute
      } else if (stdout.toLowerCase().includes("python")) {
        resolve(true); // Valid Python interpreter
      } else {
        resolve(false); // Not valid if output doesn't contain "python"
      }
    });
  });

  if (!isValidInterpreter) {
    // Show an alert if the interpreter is not valid
    await dialog.showMessageBox(
      new BrowserWindow({
        alwaysOnTop: true,
      }),
      {
        type: "error",
        title: "Invalid Interpreter",
        message: "The selected file is not a valid Python interpreter.",
      }
    );
    return null;
  }

  return filePath;
});

ipcMain.handle("get-file-content", async (event, path) => {
  try {
    const file_content = fs.readFileSync(path, "utf8");
    return file_content;
  } catch {
    return "Got error fetching file content";
  }
});

ipcMain.handle("run-code", async (event, data) => {
  try {
    if (!data.path.endsWith(".py")) {
      if (data.path.endsWith(".js")) {
        ptyProcess.write(`node ${data.path}\n`);
      }
      return;
    }

    // @ts-ignore
    const vars = store.get(DATASTUDIO_VARIABLES_STORE_NAME);

    const content = fs.readFileSync(data.path, "utf8");

    const words = content.split(/\s+/);

    vars.map((data: any) => {
      for (let word of words) {
        data.name === word
          ? event.sender.send("show-tools", data)
          : console.log(data.name, words);
      }
    });
  } catch (err) {
    await dialog.showMessageBox(
      new BrowserWindow({
        alwaysOnTop: true,
      }),
      {
        type: "error",
        title: "Invalid",
        message: err,
      }
    );
  }
  try {
    ptyProcess.write(`${data.script} ${data.path}\n`);
  } catch (err) {
    await dialog.showMessageBox(
      new BrowserWindow({
        alwaysOnTop: true,
      }),
      {
        type: "error",
        title: "Invalid",
        message: "Error when running, Try again later.",
      }
    );
  }
});

ipcMain.handle("get-variables", async (event, filePath: string) => {
  try {
    if (!filePath.endsWith(".py")) {
      return { error: "Only Python files are allowed." };
    }

    const fileContent = fs.readFileSync(filePath, "utf8");

    const variableRegex = /^([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$/gm;

    const variables: Variable[] = [];
    let match;

    while ((match = variableRegex.exec(fileContent)) !== null) {
      const name = match[1];
      const rawValue = match[2].trim();

      let value: any = rawValue;
      let type = "string";

      try {
        if (!isNaN(Number(rawValue))) {
          value = Number(rawValue);
          type = "number";
        } else if (rawValue === "True" || rawValue === "False") {
          value = rawValue === "True";
          type = "boolean";
        } else if (rawValue === "None") {
          value = null;
          type = "null";
        } else if (rawValue.startsWith("[") && rawValue.endsWith("]")) {
          value = JSON.parse(rawValue.replace(/'/g, '"'));
          type = "list";
        } else if (rawValue.startsWith("{") && rawValue.endsWith("}")) {
          value = JSON.parse(rawValue.replace(/'/g, '"'));
          type = "dict";
        } else if (rawValue.startsWith("(") && rawValue.endsWith(")")) {
          value = JSON.parse(
            rawValue.replace(/'/g, '"').replace(/^\(|\)$/g, "[") + "]"
          );
          type = "tuple";
        } else if (rawValue.startsWith("set(") && rawValue.endsWith(")")) {
          const setContent = rawValue.slice(4, -1).replace(/^\{|\}$/g, "");
          value = new Set(JSON.parse(`[${setContent.replace(/'/g, '"')}]`));
          type = "set";
        } else {
          value = rawValue.replace(/^["']|["']$/g, "");
        }
      } catch (parseError) {}

      variables.push({ name, type, value });
    }

    return { vars: variables };
  } catch (err) {
    return { error: "Failed to process the file." };
  }
});

ipcMain.handle("get-data-studio-variables", (event) => {
  // @ts-ignore
  return store.get(DATASTUDIO_VARIABLES_STORE_NAME);
});

ipcMain.on("set-data-studio-variables", (event, data) => {
  // @ts-ignore
  return store.set(DATASTUDIO_VARIABLES_STORE_NAME, data);
});

ipcMain.on("coming-soon-dialog", async (event, data) => {
  await dialog.showMessageBox(mainWindow, {
    title: "Coming Soon",
    type: "info",
    buttons: ["OK", "Cancel"],
    message: "This feature is coming soon!",
  });
});

function deleteDirectoryRecursive(dirPath: string) {
  fs.rmdirSync(dirPath);
}

let copiedFile: any = null; // Variable to store copied file data

ipcMain.on("new-folder-input", (event, data) => {
  event.sender.send("command-create-folder", data);
});
ipcMain.on("new-file-input", (event, data) => {
  event.sender.send("command-create-file", data);
});

ipcMain.on("folder-contextmenu", async (event, data) => {
  const template: any = [
    {
      label: "New File...",
      click: () => {
        event.sender.send("command-create-file", data);
      },
      visible: data.type == "folder",
    },
    {
      label: "New Folder...",
      click: () => {
        event.sender.send("command-create-folder", data);
      },
      visible: data.type == "folder",
    },
    { type: "separator" },
    {
      label: "Cut",
      role: "cut",
      click: () => {
        // Implement Cut functionality here
      },
      enabled: true, // Ensure that enabled is set if needed
    },
    {
      label: "Copy",
      role: "copy",

      enabled: true,
    },
    {
      label: "Paste",
      role: "paste",
    },
    {
      label: "Copy Relative Path",
    },
    { type: "separator" },
    {
      label: "Rename",
      role: "editMenu",
      click: () => {
        // Implement Rename functionality here
      },
    },
    {
      label: "Delete",
      click: async () => {
        console.log(data);
        if (data.type === "file") {
          fs.rmSync(data.path);
        } else {
          deleteDirectoryRecursive(data.path);
        }
      },
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  menu.popup({ window: BrowserWindow.fromWebContents(event.sender) });
});

ipcMain.on("datavarinfotitle-contextmenu", async (event, data) => {
  const template: any = [
    {
      label: "Copy Name",
      click: () => {},
    },
    { type: "separator" },
    {
      label: "Copy Name",
      click: () => {},
    },
  ];

  const menu = Menu.buildFromTemplate(template);
  menu.popup({ window: BrowserWindow.fromWebContents(event.sender) });
});

ipcMain.on("save-file", async (event, data) => {
  const file_content = fs.writeFileSync(data.path, data.content);
  console.log("file writen");
});

ipcMain.on("minimize", () => {
  mainWindow.minimize();
});

ipcMain.on("maximize", () => {
  if (mainWindow.isMaximized()) {
    mainWindow.minimize();
  } else {
    mainWindow.maximize();
  }
});

ipcMain.on("close", () => {
  mainWindow.close();
});

ipcMain.on("send-tools-data", (event, data) => {
  mainWindow.webContents.send("update-tools-data", data); // Forward to renderer
});

ipcMain.handle("read-excel-file", async (event, filePath, skipRows) => {
  try {
    // Read the file from the filesystem
    const fileBuffer = fs.readFileSync(filePath);
    const workbook = XLSX.read(fileBuffer, { type: "buffer" });

    // Get the first sheet (dynamic)
    const sheetName = workbook.SheetNames[0];
    const sheet = workbook.Sheets[sheetName];
    let jsonData = XLSX.utils.sheet_to_json(sheet, { header: 1 });

    // Skip the rows if needed
    if (skipRows > 0) {
      jsonData = jsonData.slice(skipRows);
    }

    return jsonData; // Send data to renderer
  } catch (error) {
    console.error("Error reading Excel file:", error);
    return []; // In case of an error, return an empty array
  }
});

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // nodeIntegration: true,
    },
    // zoomToPageWidth: true,
  });

  mainWindow.setMenuBarVisibility(false);

  mainWindow.maximize();

  // @ts-ignore
  const cwd = store.get(SELECTED_FOLDER_STORE_NAME).root;

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  const shell = os.platform() === "win32" ? "powershell.exe" : "bash";

  ptyProcess = pty.spawn(shell, [], {
    name: "xterm-color",
    cols: 80,
    rows: 30,
    cwd: cwd || process.env.HOME,
    env: process.env,
  });

  ptyProcess.onData(function (data) {
    mainWindow.webContents.send("terminal.incomingData", data);
    console.log("Data sent");
  });

  ipcMain.on("terminal.keystroke", (event, key) => {
    ptyProcess.write(key);
  });

  ipcMain.on("terminal.resize", (event, data) => {
    ptyProcess.resize(data.cols, data.rows);
  });

  ipcMain.on("terminal.write", (event, line) => {
    ptyProcess.write(line);
  });

  ipcMain.handle("open-folder", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });
    let structure = undefined;
    if (!folder.canceled) {
      const tree = get_files(folder.filePaths[0]);
      structure = {
        // name: path.dirname(folder.filePaths[0]),
        name: folder.filePaths[0],
        root: folder.filePaths[0],
        tree,
      };
      // @ts-ignore
      store.set(SELECTED_FOLDER_STORE_NAME, structure);
    }

    return structure;
  });

  // Register the ipcMain handler for 'dialog:openFolder'
  ipcMain.handle("open-folder-new-project", async (event, data) => {
    const folder = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });

    return folder.filePaths[0]; // Return the selected folder pathr;
  });

  mainWindow.once("ready-to-show", () => {
    mainWindow.show(); // Show the main window
  });

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

const createToolsWindow = () => {
  if (!toolsWindow) {
    toolsWindow = new BrowserWindow({
      height: 800,
      width: 1200,
      show: false,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        // nodeIntegration: true,
      },
    });

    toolsWindow.loadURL(TOOLS_WINDOW_WEBPACK_ENTRY);

    toolsWindow.setMenuBarVisibility(false);

    toolsWindow.on("closed", () => {
      toolsWindow = null;
      mainWindow.webContents.send("tools-window-closed");
    });
  }
};

ipcMain.handle("show-tools", () => {
  createToolsWindow();

  if (toolsWindow && toolsWindow.isMinimized()) {
    toolsWindow.restore();
  }

  toolsWindow?.show();
});

ipcMain.handle("hide-tools", () => {
  if (toolsWindow) {
    toolsWindow.hide();
  }
});

const createDataStudioWindow = () => {
  if (!dataStudio) {
    dataStudio = new BrowserWindow({
      height: 800,
      width: 1200,
      show: false,
      frame: false,
      webPreferences: {
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        // nodeIntegration: true,
      },
    });

    dataStudio.loadFile("./src/dataStudio.html");

    dataStudio.setMenuBarVisibility(false);

    dataStudio.on("closed", () => {
      dataStudio = null;
      mainWindow.webContents.send("datastudio-window-closed");
    });
  }
};

ipcMain.handle("show-datastudio", () => {
  createDataStudioWindow();

  if (dataStudio && dataStudio.isMinimized()) {
    dataStudio.restore();
  }

  dataStudio?.show();
});

ipcMain.handle("hide-datastudio", () => {
  if (dataStudio) {
    dataStudio.hide();
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow(); // Create the main window
  createToolsWindow();

  // Check for updates on startup
  autoUpdater.checkForUpdates();

  autoUpdater.on("update-available", () => {
    dialog.showMessageBox({
      type: "info",
      title: "Update Available",
      message:
        "A new version of the Anantam is available. The update will be downloaded and installed automatically.",
    });
  });

  autoUpdater.on("update-downloaded", () => {
    dialog
      .showMessageBox({
        type: "info",
        title: "Update Ready",
        message:
          "The update has been downloaded. Anantam will restart to apply the update.",
      })
      .then(() => {
        autoUpdater.quitAndInstall();
      });
  });

  autoUpdater.on("error", (error) => {
    console.error("Update error:", error);
  });
});
// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
