name: Release Anantam

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          yarn global add node-gyp
          yarn install --frozen-lockfile --network-timeout 1000000

      - name: Build Windows ZIP
        run: yarn make --platform win32
        env:
          WINEARCH: win64
          WINEPREFIX: /root/.wine

      - name: Build Linux ZIP
        run: yarn make --platform linux

      - name: list files
        run: |
          ls out/make

      - name: Upload Windows ZIP
        uses: actions/upload-artifact@v4
        with:
          name: anantam-windows
          path: out/make/**/*.zip

      - name: Upload Linux ZIP
        uses: actions/upload-artifact@v4
        with:
          name: anantam-linux
          path: out/make/**/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows EXE
        uses: actions/download-artifact@v4
        with:
          name: anantam-windows
          path: dist/

      - name: Download Linux DEB
        uses: actions/download-artifact@v4
        with:
          name: anantam-linux
          path: dist/

      - name: Get latest tag
        id: get_latest_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag }}
          files: dist/*
          token: ${{ secrets.GITHUB_TOKEN }}
